package com.google.android.gms.b;

import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.d;
import com.google.android.gms.common.api.g;
import com.google.android.gms.common.api.h;

public final class an<R extends g>
  extends d<R>
{
  final Status a;
  
  public final void a(h<? super R> paramh)
  {
    throw new UnsupportedOperationException("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
  }
}


/* Location:              com/google/android/gms/b/an.class
 * Java compiler version: 6 (50.0)
 * JD-Core Version:       0.7.1
 */