package com.google.android.gms.b;

import com.google.android.gms.common.api.Status;
import com.google.android.gms.common.api.d;
import com.google.android.gms.common.api.h;

public final class an
  extends d
{
  final Status a;
  
  public final void a(h paramh)
  {
    UnsupportedOperationException localUnsupportedOperationException = new java/lang/UnsupportedOperationException;
    localUnsupportedOperationException.<init>("Operation not supported on PendingResults generated by ResultTransform.createFailedResult()");
    throw localUnsupportedOperationException;
  }
}


/* Location:              com/google/android/gms/b/an.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */