package com.google.android.gms.b;

import android.content.Context;
import com.google.android.gms.ads.internal.w;
import java.util.Collection;
import java.util.Iterator;
import java.util.List;
import java.util.concurrent.Callable;
import java.util.concurrent.TimeUnit;

public final class ke
{
  public static final jz A;
  public static final jz B;
  public static final jz C;
  public static final jz D;
  public static final jz E;
  public static final jz F;
  public static final jz G;
  public static final jz H;
  public static final jz I;
  public static final jz J;
  public static final jz K;
  public static final jz L;
  public static final jz M;
  public static final jz N;
  public static final jz O;
  public static final jz P;
  public static final jz Q;
  public static final jz R;
  public static final jz S;
  public static final jz T;
  public static final jz U;
  public static final jz V;
  public static final jz W;
  public static final jz X;
  public static final jz Y;
  public static final jz Z;
  public static final jz a;
  public static final jz aA;
  public static final jz aB;
  public static final jz aC;
  public static final jz aD;
  public static final jz aE;
  public static final jz aF;
  public static final jz aG;
  public static final jz aH;
  public static final jz aI;
  public static final jz aJ;
  public static final jz aK;
  public static final jz aL;
  public static final jz aM;
  public static final jz aN;
  public static final jz aO;
  public static final jz aP;
  public static final jz aQ;
  public static final jz aR;
  public static final jz aS;
  public static final jz aT;
  public static final jz aU;
  public static final jz aV;
  public static final jz aW;
  public static final jz aX;
  public static final jz aY;
  public static final jz aZ;
  public static final jz aa;
  public static final jz ab;
  public static final jz ac;
  public static final jz ad;
  public static final jz ae;
  public static final jz af;
  public static final jz ag;
  public static final jz ah;
  public static final jz ai;
  public static final jz aj;
  public static final jz ak;
  public static final jz al;
  public static final jz am;
  public static final jz an;
  public static final jz ao;
  public static final jz ap;
  public static final jz aq;
  public static final jz ar;
  public static final jz as;
  public static final jz at;
  public static final jz au;
  public static final jz av;
  public static final jz aw;
  public static final jz ax;
  public static final jz ay;
  public static final jz az;
  public static final jz b;
  public static final jz bA;
  public static final jz bB;
  public static final jz bC;
  public static final jz bD;
  public static final jz bE;
  public static final jz bF;
  public static final jz bG;
  public static final jz bH;
  public static final jz bI;
  public static final jz bJ;
  public static final jz bK;
  public static final jz bL;
  public static final jz bM;
  public static final jz bN;
  public static final jz bO;
  public static final jz bP;
  public static final jz bQ;
  public static final jz bR;
  public static final jz bS;
  public static final jz bT;
  public static final jz bU;
  public static final jz bV;
  public static final jz bW;
  public static final jz bX;
  public static final jz bY;
  public static final jz bZ;
  public static final jz ba;
  public static final jz bb;
  public static final jz bc;
  public static final jz bd;
  public static final jz be;
  public static final jz bf;
  public static final jz bg;
  public static final jz bh;
  public static final jz bi;
  public static final jz bj;
  public static final jz bk;
  public static final jz bl;
  public static final jz bm;
  public static final jz bn;
  public static final jz bo;
  public static final jz bp;
  public static final jz bq;
  public static final jz br;
  public static final jz bs;
  public static final jz bt;
  public static final jz bu;
  public static final jz bv;
  public static final jz bw;
  public static final jz bx;
  public static final jz by;
  public static final jz bz;
  public static final jz c;
  public static final jz cA;
  public static final jz cB;
  public static final jz cC;
  public static final jz cD;
  public static final jz cE;
  public static final jz cF;
  public static final jz cG;
  public static final jz cH;
  public static final jz cI;
  public static final jz cJ;
  public static final jz cK;
  public static final jz cL;
  public static final jz cM;
  public static final jz cN;
  public static final jz cO;
  public static final jz cP;
  public static final jz cQ;
  public static final jz cR;
  public static final jz cS;
  public static final jz cT;
  public static final jz cU;
  public static final jz cV;
  public static final jz cW;
  public static final jz cX;
  public static final jz cY;
  public static final jz cZ;
  public static final jz ca;
  public static final jz cb;
  public static final jz cc;
  public static final jz cd;
  public static final jz ce;
  public static final jz cf;
  public static final jz cg;
  public static final jz ch;
  public static final jz ci;
  public static final jz cj;
  public static final jz ck;
  public static final jz cl;
  public static final jz cm;
  public static final jz cn;
  public static final jz co;
  public static final jz cp;
  public static final jz cq;
  public static final jz cr;
  public static final jz cs;
  public static final jz ct;
  public static final jz cu;
  public static final jz cv;
  public static final jz cw;
  public static final jz cx;
  public static final jz cy;
  public static final jz cz;
  public static final jz d;
  public static final jz da;
  public static final jz db;
  public static final jz dc;
  public static final jz dd;
  public static final jz de;
  public static final jz df;
  public static final jz dg;
  public static final jz dh;
  public static final jz di;
  public static final jz dj;
  public static final jz dk;
  public static final jz dl;
  public static final jz dm;
  public static final jz dn;
  public static final jz jdField_do;
  public static final jz dp;
  private static byte[] dq;
  public static final jz e;
  public static final jz f;
  public static final jz g;
  public static final jz h;
  public static final jz i;
  public static final jz j;
  public static final jz k;
  public static final jz l;
  public static final jz m;
  public static final jz n;
  public static final jz o;
  public static final jz p;
  public static final jz q;
  public static final jz r;
  public static final jz s;
  public static final jz t;
  public static final jz u;
  public static final jz v;
  public static final jz w;
  public static final jz x;
  public static final jz y;
  public static final jz z;
  
  static
  {
    int i1 = 10;
    int i2 = 3;
    long l1 = 2000L;
    int i3 = 1;
    a = jz.a(0, "gads:sdk_core_experiment_id");
    b = jz.a(0, "gads:sdk_core_location", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/sdk-core-v40.html");
    Boolean localBoolean = Boolean.valueOf(false);
    c = jz.a(0, "gads:request_builder:singleton_webview", localBoolean);
    d = jz.a(0, "gads:request_builder:singleton_webview_experiment_id");
    localBoolean = Boolean.valueOf(i3);
    e = jz.a(0, "gads:sdk_use_dynamic_module", localBoolean);
    f = jz.a(0, "gads:sdk_use_dynamic_module_experiment_id");
    localBoolean = Boolean.valueOf(false);
    g = jz.a(0, "gads:sdk_crash_report_enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    h = jz.a(0, "gads:sdk_crash_report_full_stacktrace", localBoolean);
    i = jz.a(0, "gads:sdk_crash_report_class_prefix", "com.google.");
    localBoolean = Boolean.valueOf(false);
    j = jz.a(0, "gads:block_autoclicks", localBoolean);
    k = jz.a(0, "gads:block_autoclicks_experiment_id");
    l = jz.a(0, "gads:spam_app_context:experiment_id");
    localBoolean = Boolean.valueOf(false);
    m = jz.a(i3, "gads:spam_app_context:enabled", localBoolean);
    n = jz.a(i3, "gads:http_url_connection_factory:timeout_millis", 10000);
    o = jz.a(i3, "gads:video_exo_player:version", "1");
    p = jz.a(0, "gads:video_stream_cache:experiment_id");
    q = jz.a(i3, "gads:video_stream_cache:limit_count", 5);
    r = jz.a(i3, "gads:video_stream_cache:limit_space", 8388608);
    s = jz.a(i3, "gads:video_stream_exo_allocator:segment_size", 65536);
    t = jz.a(i3, "gads:video_stream_exo_cache:buffer_size", 8388608);
    u = jz.a(i3, "gads:video_stream_cache:limit_time_sec", 300L);
    v = jz.a(i3, "gads:video_stream_cache:notify_interval_millis", 1000L);
    w = jz.a(i3, "gads:video_stream_cache:connect_timeout_millis", 10000);
    localBoolean = Boolean.valueOf(false);
    x = jz.a(0, "gads:video:metric_reporting_enabled", localBoolean);
    y = jz.a(i3, "gads:video:metric_frame_hash_times", "");
    z = jz.a(i3, "gads:video:metric_frame_hash_time_leniency", 500L);
    localBoolean = Boolean.valueOf(false);
    A = jz.a(i3, "gads:video:force_watermark", localBoolean);
    B = jz.a(i3, "gads:video:surface_update_min_spacing_ms", 1000L);
    localBoolean = Boolean.valueOf(false);
    C = jz.a(i3, "gads:video:spinner:enabled", localBoolean);
    D = jz.a(i3, "gads:video:spinner:scale", 4);
    E = jz.a(i3, "gads:video:spinner:jank_threshold_ms", 50);
    localBoolean = Boolean.valueOf(false);
    F = jz.a(i3, "gads:memory_bundle:debug_info", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    G = jz.a(i3, "gads:memory_bundle:runtime_info", localBoolean);
    H = jz.b(0, "gads:spam_ad_id_decorator:experiment_id");
    localBoolean = Boolean.valueOf(false);
    I = jz.a(0, "gads:spam_ad_id_decorator:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    J = jz.a(0, "gads:ad_id_app_context:enabled", localBoolean);
    K = jz.a(0, "gads:ad_id_app_context:ping_ratio", 0.0F);
    L = jz.a(0, "gads:ad_id_app_context:experiment_id");
    M = jz.b(0, "gads:looper_for_gms_client:experiment_id");
    localBoolean = Boolean.valueOf(i3);
    N = jz.a(0, "gads:looper_for_gms_client:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    O = jz.a(0, "gads:sw_ad_request_service:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    P = jz.a(0, "gads:sw_dynamite:enabled", localBoolean);
    Q = jz.a(i3, "gad:mraid:url_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_banner.js");
    R = jz.a(i3, "gad:mraid:url_expanded_banner", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_expanded_banner.js");
    S = jz.a(i3, "gad:mraid:url_interstitial", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/mraid/v2/mraid_app_interstitial.js");
    localBoolean = Boolean.valueOf(false);
    T = jz.a(0, "gads:enabled_sdk_csi", localBoolean);
    U = jz.a(0, "gads:sdk_csi_server", "https://csi.gstatic.com/csi");
    localBoolean = Boolean.valueOf(false);
    V = jz.a(0, "gads:sdk_csi_write_to_file", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    W = jz.a(0, "gads:enable_content_fetching", localBoolean);
    X = jz.a(0, "gads:content_length_weight", i3);
    Y = jz.a(0, "gads:content_age_weight", i3);
    Z = jz.a(0, "gads:min_content_len", 11);
    aa = jz.a(0, "gads:fingerprint_number", i1);
    ab = jz.a(0, "gads:sleep_sec", i1);
    localBoolean = Boolean.valueOf(i3);
    ac = jz.a(i3, "gads:enable_content_url_hash", localBoolean);
    ad = jz.a(i3, "gads:content_vertical_fingerprint_number", 100);
    localBoolean = Boolean.valueOf(i3);
    ae = jz.a(i3, "gads:enable_content_vertical_hash", localBoolean);
    af = jz.a(i3, "gads:content_vertical_fingerprint_bits", 23);
    ag = jz.a(i3, "gads:content_vertical_fingerprint_ngram", i2);
    ah = jz.a(i3, "gads:content_fetch_view_tag_id", "googlebot");
    ai = jz.a(i3, "gads:content_fetch_exclude_view_tag", "none");
    localBoolean = Boolean.valueOf(i3);
    aj = jz.a(0, "gad:app_index_enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    ak = jz.a(0, "gads:app_index:without_content_info_present:enabled", localBoolean);
    al = jz.a(0, "gads:app_index:timeout_ms", 1000L);
    am = jz.a(0, "gads:app_index:experiment_id");
    an = jz.a(0, "gads:kitkat_interstitial_workaround:experiment_id");
    localBoolean = Boolean.valueOf(i3);
    ao = jz.a(0, "gads:kitkat_interstitial_workaround:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    ap = jz.a(0, "gads:interstitial_follow_url", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    aq = jz.a(0, "gads:interstitial_follow_url:register_click", localBoolean);
    ar = jz.a(0, "gads:interstitial_follow_url:experiment_id");
    localBoolean = Boolean.valueOf(i3);
    as = jz.a(0, "gads:analytics_enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    at = jz.a(0, "gads:ad_key_enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    au = jz.a(i3, "gads:sai:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    av = jz.a(i3, "gads:sai:banner_ad_enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    aw = jz.a(i3, "gads:sai:native_ad_enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    ax = jz.a(i3, "gads:sai:interstitial_ad_enabled", localBoolean);
    ay = jz.a(i3, "gads:sai:click_ping_schema", "[\"/aclk\",\"/pcs/click\"]");
    az = jz.a(i3, "gads:sai:impression_ping_schema", "[\"/adview\"]");
    localBoolean = Boolean.valueOf(i3);
    aA = jz.a(i3, "gads:sai:click_gmsg_enabled", localBoolean);
    aB = jz.a(0, "gads:webview_cache_version", 0);
    localBoolean = Boolean.valueOf(false);
    aC = jz.a(i3, "gads:webview_recycle:enabled", localBoolean);
    aD = jz.a(i3, "gads:webview_recycle:experiment_id");
    localBoolean = Boolean.valueOf(i3);
    aE = jz.a(i3, "gads:webview:ignore_over_scroll", localBoolean);
    aF = jz.b(0, "gads:pan:experiment_id");
    aG = jz.a(i3, "gads:rewarded:experiment_id");
    localBoolean = Boolean.valueOf(false);
    aH = jz.a(i3, "gads:rewarded:adapter_initialization_enabled", localBoolean);
    aI = jz.a(i3, "gads:rewarded:adapter_timeout_ms", 20000L);
    localBoolean = Boolean.valueOf(i3);
    aJ = jz.a(i3, "gads:app_activity_tracker:enabled", localBoolean);
    aK = jz.a(i3, "gads:app_activity_tracker:notify_background_listeners_delay_ms", 500L);
    long l2 = TimeUnit.MINUTES.toMillis(5);
    aL = jz.a(i3, "gads:app_activity_tracker:app_session_timeout_ms", l2);
    localBoolean = Boolean.valueOf(false);
    aM = jz.a(i3, "gads:adid_values_in_adrequest:enabled", localBoolean);
    aN = jz.a(i3, "gads:adid_values_in_adrequest:timeout", l1);
    localBoolean = Boolean.valueOf(false);
    aO = jz.a(i3, "gads:disable_adid_values_in_ms", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    aP = jz.a(0, "gads:ad_serving:enabled", localBoolean);
    aQ = jz.a(i3, "gads:ad_manager_enforce_arp_invariant:experiment_id");
    localBoolean = Boolean.valueOf(false);
    aR = jz.a(i3, "gads:ad_manager_enforce_arp_invariant:enabled", localBoolean);
    aS = jz.a(i3, "gads:ad_overlay:delay_page_close_timeout_ms", 5000L);
    aT = jz.a(i3, "gads:banner_ad_pool:schema", "customTargeting");
    aU = jz.a(i3, "gads:banner_ad_pool:max_queues", i2);
    aV = jz.a(i3, "gads:banner_ad_pool:max_pools", i2);
    localBoolean = Boolean.valueOf(false);
    aW = jz.a(i3, "gads:interstitial_ad_pool:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    aX = jz.a(i3, "gads:interstitial_ad_pool:enabled_for_rewarded", localBoolean);
    aY = jz.a(i3, "gads:interstitial_ad_pool:schema", "customTargeting");
    aZ = jz.a(i3, "gads:interstitial_ad_pool:request_exclusions", "com.google.ads.mediation.admob.AdMobAdapter/_ad");
    ba = jz.a(i3, "gads:interstitial_ad_pool:max_pools", i2);
    bb = jz.a(i3, "gads:interstitial_ad_pool:max_pool_depth", 2);
    bc = jz.a(i3, "gads:interstitial_ad_pool:time_limit_sec", 1200);
    bd = jz.a(i3, "gads:interstitial_ad_pool:ad_unit_exclusions", "(?!)");
    be = jz.a(i3, "gads:interstitial_ad_pool:top_off_latency_min_millis", 0);
    bf = jz.a(i3, "gads:interstitial_ad_pool:top_off_latency_range_millis", 0);
    bg = jz.a(i3, "gads:interstitial_ad_pool:discard_threshold", 0.0F / 0.0F);
    bh = jz.a(i3, "gads:heap_wastage:bytes", 0);
    bi = jz.a(i3, "gads:spherical_video:vertex_shader", "");
    bj = jz.a(i3, "gads:spherical_video:fragment_shader", "");
    bk = jz.a(i3, "gads:spherical_video:experiment_id");
    localBoolean = Boolean.valueOf(false);
    bl = jz.a(0, "gads:log:verbose_enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    bm = jz.a(i3, "gads:include_local_global_rectangles", localBoolean);
    bn = jz.a(i3, "gads:include_local_global_rectangles:experiment_id");
    bo = jz.a(i3, "gads:position_watcher:throttle_ms", 200L);
    localBoolean = Boolean.valueOf(i3);
    bp = jz.a(0, "gads:device_info_caching:enabled", localBoolean);
    bq = jz.a(0, "gads:device_info_caching_expiry_ms:expiry", 300000L);
    localBoolean = Boolean.valueOf(false);
    br = jz.a(0, "gads:gen204_signals:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    bs = jz.a(0, "gads:webview:error_reporting_enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    bt = jz.a(0, "gads:adid_reporting:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    bu = jz.a(0, "gads:ad_settings_page_reporting:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    bv = jz.a(0, "gads:adid_info_gmscore_upgrade_reporting:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bw = jz.a(0, "gads:request_pkg:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bx = jz.a(i3, "gads:gmsg:disable_back_button:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    by = jz.a(0, "gads:gmsg:video_meta:enabled", localBoolean);
    bz = jz.a(0, "gads:gmsg:video_meta:experiment_id");
    bA = jz.a(i3, "gads:network:cache_prediction_duration_s", 300L);
    bB = jz.a(i3, "gads:network:network_prediction_timeout_ms", l1);
    localBoolean = Boolean.valueOf(i3);
    bC = jz.a(0, "gads:mediation:dynamite_first:admobadapter", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bD = jz.a(0, "gads:mediation:dynamite_first:adurladapter", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bE = jz.a(i3, "gads:bypass_adrequest_service_for_inlined_mediation", localBoolean);
    bF = jz.a(0, "gads:ad_loader:timeout_ms", 60000L);
    bG = jz.a(0, "gads:rendering:timeout_ms", 60000L);
    localBoolean = Boolean.valueOf(false);
    bH = jz.a(0, "gads:adshield:enable_adshield_instrumentation", localBoolean);
    bI = jz.a(i3, "gads:gestures:task_timeout", l1);
    localBoolean = Boolean.valueOf(false);
    bJ = jz.a(i3, "gads:gestures:encrypt_size_limit:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    bK = jz.a(i3, "gads:gestures:adb_query:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    bL = jz.a(i3, "gads:gestures:adb_click:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    bM = jz.a(i3, "gads:gestures:visibility:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    bN = jz.a(i3, "gads:gestures:check_initialization_thread:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bO = jz.a(i3, "gads:gestures:get_query_in_non_ui_thread:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bP = jz.a(0, "gass:client:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bQ = jz.a(0, "gass:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bR = jz.a(0, "gass:enable_int_signal", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bS = jz.a(0, "gads:adid_notification:first_party_check:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bT = jz.a(0, "gads:edu_device_helper:enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bU = jz.a(0, "gads:support_screen_shot", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    bV = jz.a(0, "gads:use_get_drawing_cache_for_screenshot:enabled", localBoolean);
    bW = jz.a(0, "gads:use_get_drawing_cache_for_screenshot:experiment_id");
    bX = jz.a(i3, "gads:sdk_core_constants:experiment_id");
    bY = jz.a(i3, "gads:sdk_core_constants:caps", "");
    l2 = TimeUnit.HOURS.toMillis(12);
    bZ = jz.a(0, "gads:js_flags:update_interval", l2);
    localBoolean = Boolean.valueOf(false);
    ca = jz.a(0, "gads:js_flags:mf", localBoolean);
    localBoolean = Boolean.valueOf(false);
    cb = jz.a(0, "gads:custom_render:ping_on_ad_rendered", localBoolean);
    cc = jz.a(0, "gads:native:engine_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    cd = jz.a(i3, "gads:native:engine_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_ads.html");
    ce = jz.a(i3, "gads:native:video_url", "//googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    cf = jz.a(i3, "gads:native:video_url_with_protocol", "https://googleads.g.doubleclick.net/mads/static/mad/sdk/native/native_video_ads.html");
    localBoolean = Boolean.valueOf(false);
    cg = jz.a(i3, "gads:singleton_webview_native", localBoolean);
    localBoolean = Boolean.valueOf(false);
    ch = jz.a(i3, "gads:native_initialize_Webview_request_time", localBoolean);
    ci = jz.a(i3, "gads:singleton_webview_native:experiment_id");
    localBoolean = Boolean.valueOf(i3);
    cj = jz.a(i3, "gads:enable_untrack_view_native", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    ck = jz.a(i3, "gads:ignore_untrack_view_google_native", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    cl = jz.a(i3, "gads:reset_listeners_preparead_native", localBoolean);
    cm = jz.a(i3, "gads:native_video_load_timeout", i1);
    cn = jz.a(i3, "gads:native_video_load_timeout:experiment_id");
    co = jz.a(i3, "gads:ad_choices_content_description", "Ad Choices Icon");
    localBoolean = Boolean.valueOf(i3);
    cp = jz.a(i3, "gads:clamp_native_video_player_dimensions", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    cq = jz.a(i3, "gads:enable_tracking_for_native_ad_views", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    cr = jz.a(i3, "gads:use_new_json_for_native_view_tracking", localBoolean);
    localBoolean = Boolean.valueOf(false);
    cs = jz.a(i3, "gads:fluid_ad:use_wrap_content_height", localBoolean);
    localBoolean = Boolean.valueOf(false);
    ct = jz.a(0, "gads:method_tracing:enabled", localBoolean);
    cu = jz.a(0, "gads:method_tracing:duration_ms", 30000L);
    cv = jz.a(0, "gads:method_tracing:count", 5);
    cw = jz.a(0, "gads:method_tracing:filesize", 134217728);
    localBoolean = Boolean.valueOf(false);
    cx = jz.a(i3, "gads:auto_location_for_coarse_permission", localBoolean);
    cy = jz.b(i3, "gads:auto_location_for_coarse_permission:experiment_id");
    cz = jz.a(i3, "gads:auto_location_timeout", l1);
    cA = jz.b(i3, "gads:auto_location_timeout:experiment_id");
    cB = jz.a(i3, "gads:auto_location_interval", -1);
    cC = jz.b(i3, "gads:auto_location_interval:experiment_id");
    localBoolean = Boolean.valueOf(false);
    cD = jz.a(i3, "gads:fetch_app_settings_using_cld:enabled", localBoolean);
    cE = jz.a(i3, "gads:fetch_app_settings_using_cld:enabled:experiment_id");
    cF = jz.a(i3, "gads:fetch_app_settings_using_cld:refresh_interval_ms", 7200000L);
    cG = jz.a(i3, "gads:fetch_app_settings_using_cld:refresh_interval_ms:experiment_id");
    cH = jz.a(0, "gads:afs:csa:experiment_id");
    cI = jz.a(0, "gads:afs:csa_webview_gmsg_ad_failed", "gmsg://noAdLoaded");
    cJ = jz.a(0, "gads:afs:csa_webview_gmsg_script_load_failed", "gmsg://scriptLoadFailed");
    cK = jz.a(0, "gads:afs:csa_webview_gmsg_ad_loaded", "gmsg://adResized");
    cL = jz.a(0, "gads:afs:csa_webview_static_file_path", "/afs/ads/i/webview.html");
    cM = jz.a(0, "gads:afs:csa_webview_custom_domain_param_key", "csa_customDomain");
    cN = jz.a(0, "gads:afs:csa_webview_adshield_timeout_ms", 1000L);
    localBoolean = Boolean.valueOf(i3);
    cO = jz.a(0, "gads:afs:csa_ad_manager_enabled", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    cP = jz.a(i3, "gads:parental_controls:send_from_client", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    cQ = jz.a(i3, "gads:parental_controls:cache_results", localBoolean);
    cR = jz.a(i3, "gads:parental_controls:timeout", l1);
    cS = jz.a(0, "gads:safe_browsing:api_key", "AIzaSyDRKQ9d6kfsoZT2lUnZcZnBYvH69HExNPE");
    cT = jz.a(0, "gads:safe_browsing:safety_net:delay_ms", l1);
    localBoolean = Boolean.valueOf(false);
    cU = jz.a(0, "gads:safe_browsing:debug", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    cV = jz.a(0, "gads:webview_cookie:enabled", localBoolean);
    cW = jz.a(i3, "gads:cache:max_concurrent_downloads", i1);
    cX = jz.a(i3, "gads:cache:javascript_timeout_millis", 5000L);
    localBoolean = Boolean.valueOf(false);
    cY = jz.a(i3, "gads:cache:bind_on_foreground", localBoolean);
    localBoolean = Boolean.valueOf(false);
    cZ = jz.a(i3, "gads:cache:bind_on_init", localBoolean);
    localBoolean = Boolean.valueOf(false);
    da = jz.a(i3, "gads:cache:bind_on_request", localBoolean);
    l2 = TimeUnit.SECONDS.toMillis(30);
    db = jz.a(i3, "gads:cache:bind_on_request_keep_alive", l2);
    localBoolean = Boolean.valueOf(false);
    dc = jz.a(i3, "gads:cache:use_cache_data_source", localBoolean);
    localBoolean = Boolean.valueOf(i3);
    dd = jz.a(i3, "gads:chrome_custom_tabs:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    de = jz.a(i3, "gads:chrome_custom_tabs:disabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    df = jz.a(i3, "gads:drx_in_app_preview:enabled", localBoolean);
    localBoolean = Boolean.valueOf(false);
    dg = jz.a(i3, "gads:drx_debug_signals:enabled", localBoolean);
    dh = jz.a(i3, "gads:drx_debug:debug_device_linking_url", "https://www.google.com/dfp/linkDevice");
    di = jz.a(i3, "gads:drx_debug:in_app_preview_status_url", "https://www.google.com/dfp/inAppPreview");
    dj = jz.a(i3, "gads:drx_debug:debug_signal_status_url", "https://www.google.com/dfp/debugSignals");
    dk = jz.a(i3, "gads:drx_debug:send_debug_data_url", "https://www.google.com/dfp/sendDebugData");
    dl = jz.a(i3, "gads:drx_debug:timeout_ms", 5000);
    dm = jz.a(i3, "gad:pixel_dp_comparision_multiplier", i3);
    localBoolean = Boolean.valueOf(false);
    dn = jz.a(i3, "gad:interstitial_for_multi_window", localBoolean);
    localBoolean = Boolean.valueOf(false);
    do = jz.a(i3, "gad:interstitial_ad_stay_active_in_multi_window", localBoolean);
    dp = jz.a(i3, "gad:interstitial:close_button_padding_dip", 0);
  }
  
  public static List a()
  {
    return w.p().a();
  }
  
  public static void a(Context paramContext)
  {
    Object localObject1 = new com/google/android/gms/b/ke$1;
    ((ke.1)localObject1).<init>(paramContext);
    uh.a((Callable)localObject1);
    localObject1 = bh;
    Object localObject2 = w.q();
    localObject1 = (Integer)((kd)localObject2).a((jz)localObject1);
    int i1 = ((Integer)localObject1).intValue();
    if (i1 > 0)
    {
      localObject2 = dq;
      if (localObject2 == null)
      {
        localObject1 = new byte[i1];
        dq = (byte[])localObject1;
      }
    }
  }
  
  public static List b()
  {
    Object localObject = w.p();
    List localList = ((kb)localObject).a();
    localObject = c;
    Iterator localIterator = ((Collection)localObject).iterator();
    for (;;)
    {
      boolean bool = localIterator.hasNext();
      if (!bool) {
        break;
      }
      localObject = (jz)localIterator.next();
      kd localkd = w.q();
      localObject = (String)localkd.a((jz)localObject);
      if (localObject != null) {
        localList.add(localObject);
      }
    }
    return localList;
  }
}


/* Location:              com/google/android/gms/b/ke.class
 * Java compiler version: 5 (49.0)
 * JD-Core Version:       0.7.1
 */